#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: localhost:8080
#
#  application:
#    name: nacos-provider
#
#
#server:
#  port: 8082
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"